server:
  port: 8082
  servlet:
    context-path: /
spring:
  profiles:
    active: test
mybatis:
  mapper-locations: classpath:com/ding/hddk/dao/mapper/**.xml
  type-aliases-package: com.ding.hddk.domain
mapper:
  mappers: com.ding.hddk.base.BaseMapper
